apiVersion: v1
kind: Service
metadata:
  name: controller-cluster
  labels:
    app: boundary
spec:
  ports:
    - name: api
      port: 9201
      protocol: TCP
      targetPort: 9201
  selector:
    app: boundary
    type: controller