apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  labels:
    app: boundary
data:
  boundary.hcl: |
    disable_mlock = true

    controller {
      name        = "env://POD_NAME"
      description = "Boundary controller"

      database {
        url = "env://POSTGRES_CONNECTION"
      }

      public_cluster_addr = "env://CONTROLLER_CLUSTER_SERVICE_HOST"
    }

    # Public API listener configuration blocks
    listener "tcp" {
      address       = "[::]:9200"
      purpose       = "api"
      tls_cert_file = "/boundary/userconfig/tls/tls.crt"
      tls_key_file  = "/boundary/userconfig/tls/tls.key"
    }

    # Data-plane listener configuration block (used for worker coordination)
    listener "tcp" {
      address = "[::]:9201"
      purpose = "cluster"
    }

    kms "transit" {
      purpose         = "root"
      address         = "https://vault.vault.svc.cluster.local:8200"
      disable_renewal = "false"

      key_name   = "boundary"
      mount_path = "transit/"
      namespace  = "root/"

      tls_skip_verify = "true"
    }

    kms "transit" {
      purpose         = "worker-auth"
      address         = "https://vault.vault.svc.cluster.local:8200"
      disable_renewal = "false"

      key_name   = "boundary"
      mount_path = "transit/"
      namespace  = "root/"

      tls_skip_verify = "true"
    }

    kms "transit" {
      purpose         = "recovery"
      address         = "https://vault.vault.svc.cluster.local:8200"
      disable_renewal = "false"

      key_name   = "boundary"
      mount_path = "transit/"
      namespace  = "root/"

      tls_skip_verify    = "true"
    }