apiVersion: v1
kind: Service
metadata:
  name: controller-api
  labels:
    app: boundary
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: boundary
    type: controller