apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: boundary
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          volumeMounts:
            - name: postgresql-disk
              mountPath: /data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: database
      volumes:
        - name: psql-creds
          secret:
            secretName: psql-creds
  volumeClaimTemplates:
    - metadata:
        name: postgresql-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi