apiVersion: v1
kind: Service
metadata:
  name: worker-proxy
  labels:
    app: boundary
spec:
  clusterIP: None
  ports:
    - port: 9202
      protocol: TCP
      targetPort: 9202
  selector:
    app: boundary
    type: worker